# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ebc9ac1f5da8598f87032b414a4dd5fa"
name = "Brisk Testing App"
handle = "brisk-testing-app"
application_url = "https://fd1f-2400-adc5-406-6300-5834-682-c011-b98f.ngrok-free.app"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "checkout-testing-app.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_checkout_branding_settings,read_customers,read_delivery_customizations,read_orders,read_payment_customizations,write_checkout_branding_settings,write_delivery_customizations,write_files,write_payment_customizations,write_products"
use_legacy_install_flow = true

[auth]
redirect_urls = [
  "https://fd1f-2400-adc5-406-6300-5834-682-c011-b98f.ngrok-free.app/auth/callback",
  "https://fd1f-2400-adc5-406-6300-5834-682-c011-b98f.ngrok-free.app/auth/shopify/callback",
  "https://fd1f-2400-adc5-406-6300-5834-682-c011-b98f.ngrok-free.app/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
