# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "273883ae6186396e66741661b1f260ef"
name = "jj-testing-brisk"
handle = "jj-testing-brisk"
application_url = "https://0c25-139-135-38-72.ngrok-free.app"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "checkout-testing-app.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_checkout_branding_settings,read_customers,read_delivery_customizations,read_orders,read_payment_customizations,write_checkout_branding_settings,write_delivery_customizations,write_files,write_payment_customizations,write_products"

[auth]
redirect_urls = [
  "https://0c25-139-135-38-72.ngrok-free.app/auth/callback",
  "https://0c25-139-135-38-72.ngrok-free.app/auth/shopify/callback",
  "https://0c25-139-135-38-72.ngrok-free.app/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
