# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ee6dce8d57fca5227655ce4f69dfc19f"
name = "brisk"
application_url = "https://pension-packard-mistress-aim.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "development-store-checkout.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://pension-packard-mistress-aim.trycloudflare.com/auth/callback",
  "https://pension-packard-mistress-aim.trycloudflare.com/auth/shopify/callback",
  "https://pension-packard-mistress-aim.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false
